// Complete content matrix: platform × format × purpose
// Every combination has a suggested strategy in format-guides.ts

export type ContentPlatform =
  | 'instagram'
  | 'tiktok'
  | 'youtube'
  | 'linkedin'
  | 'twitter'
  | 'facebook'
  | 'whatsapp'
  | 'newsletter'

export type ContentFormat =
  // Instagram
  | 'feed_photo'
  | 'carousel'
  | 'reels'
  | 'story'
  | 'story_highlight'
  | 'live'
  | 'ugc'
  | 'meme'
  // TikTok
  | 'short_video'
  | 'duet'
  | 'stitch'
  | 'photo_carousel'
  | 'tiktok_live'
  | 'tiktok_ugc'
  // YouTube
  | 'long_video'
  | 'youtube_shorts'
  | 'community_post'
  | 'podcast_video'
  // LinkedIn
  | 'text_post'
  | 'single_image'
  | 'document_carousel'
  | 'video_post'
  | 'linkedin_newsletter'
  | 'poll'
  | 'article'
  // Twitter/X
  | 'text_tweet'
  | 'thread'
  | 'image_tweet'
  | 'video_tweet'
  | 'spaces'
  // Facebook
  | 'fb_post'
  | 'fb_reels'
  | 'fb_story'
  | 'event'
  | 'group_post'
  | 'fb_live'
  // WhatsApp
  | 'status_text'
  | 'status_image'
  | 'status_video'
  | 'community_announcement'
  | 'broadcast'
  // Newsletter
  | 'solo'
  | 'digest'
  | 'sequence'
  | 'welcome'

export type ContentPurpose =
  | 'educate'
  | 'entertain'
  | 'inspire'
  | 'sell'
  | 'engage'
  | 'convert'
  | 'authority'
  | 'community'
  | 'culture'

export interface FormatConfig {
  id: ContentFormat
  label: string
  description: string
  icon: string
  visualType: 'image' | 'video' | 'text' | 'mixed' | 'audio'
  aspectRatio: '1:1' | '4:5' | '9:16' | '16:9' | '1200:627' | 'text'
  maxDuration?: string
  maxLength?: string
  requiresVisual: boolean
  aiGeneratesVisual: boolean
  aiGeneratesCopy: boolean
  suggestedCadence: string
  bestTimeToPost: string
  engagementLevel: 'high' | 'medium' | 'low'
  productionEffort: 'low' | 'medium' | 'high'
}

export interface PlatformConfig {
  id: ContentPlatform
  label: string
  icon: string
  description: string
  audience: string
  formats: ContentFormat[]
  bestDays: string[]
  bestTimes: string[]
  primaryPurpose: ContentPurpose[]
  contentRatio: Record<ContentPurpose, number>
}

export const PLATFORMS: Record<ContentPlatform, PlatformConfig> = {
  instagram: {
    id: 'instagram',
    label: 'Instagram',
    icon: 'instagram',
    description: 'Principal vitrine visual. Comunidade, lifestyle e descoberta.',
    audience: 'Brasileiros 18-45 no exterior. Visual-first.',
    formats: ['feed_photo', 'carousel', 'reels', 'story', 'story_highlight', 'live', 'ugc', 'meme'],
    bestDays: ['Tue', 'Wed', 'Thu'],
    bestTimes: ['08:00', '12:00', '18:00'],
    primaryPurpose: ['inspire', 'educate', 'community', 'entertain'],
    contentRatio: {
      educate: 30,
      entertain: 20,
      inspire: 20,
      sell: 10,
      engage: 10,
      convert: 5,
      authority: 3,
      community: 2,
      culture: 0,
    },
  },
  tiktok: {
    id: 'tiktok',
    label: 'TikTok',
    icon: 'tiktok',
    description: 'Alcance orgânico viral. Dicas rápidas, personalidade, trends.',
    audience: 'Brasileiros 18-35. Entretenimento + utilidade.',
    formats: ['short_video', 'duet', 'stitch', 'photo_carousel', 'tiktok_live', 'tiktok_ugc'],
    bestDays: ['Tue', 'Thu', 'Fri'],
    bestTimes: ['07:00', '12:00', '19:00'],
    primaryPurpose: ['entertain', 'educate', 'culture', 'community'],
    contentRatio: {
      educate: 35,
      entertain: 30,
      inspire: 5,
      sell: 5,
      engage: 10,
      convert: 5,
      authority: 0,
      community: 5,
      culture: 5,
    },
  },
  youtube: {
    id: 'youtube',
    label: 'YouTube',
    icon: 'youtube',
    description: 'SEO de longo prazo. Tutoriais profundos e podcast.',
    audience: 'Brasileiros buscando respostas detalhadas. 22-50.',
    formats: ['long_video', 'youtube_shorts', 'community_post', 'podcast_video'],
    bestDays: ['Thu', 'Sat', 'Sun'],
    bestTimes: ['14:00', '16:00'],
    primaryPurpose: ['educate', 'authority', 'inspire', 'community'],
    contentRatio: {
      educate: 50,
      entertain: 10,
      inspire: 10,
      sell: 5,
      engage: 10,
      convert: 5,
      authority: 5,
      community: 5,
      culture: 0,
    },
  },
  linkedin: {
    id: 'linkedin',
    label: 'LinkedIn',
    icon: 'linkedin',
    description: 'Autoridade profissional. Carreira, networking, B2B.',
    audience: 'Brasileiros profissionais no exterior. 25-55.',
    formats: [
      'text_post',
      'single_image',
      'document_carousel',
      'video_post',
      'linkedin_newsletter',
      'poll',
      'article',
    ],
    bestDays: ['Tue', 'Wed', 'Thu'],
    bestTimes: ['08:00', '12:00', '17:00'],
    primaryPurpose: ['authority', 'educate', 'inspire', 'convert'],
    contentRatio: {
      educate: 35,
      entertain: 5,
      inspire: 20,
      sell: 10,
      engage: 10,
      convert: 10,
      authority: 5,
      community: 5,
      culture: 0,
    },
  },
  twitter: {
    id: 'twitter',
    label: 'Twitter/X',
    icon: 'twitter',
    description: 'Opinião, threads educativas, engajamento em tempo real.',
    audience: 'Brasileiros tech/profissionais. 20-45.',
    formats: ['text_tweet', 'thread', 'image_tweet', 'video_tweet', 'spaces'],
    bestDays: ['Mon', 'Tue', 'Wed', 'Thu'],
    bestTimes: ['08:00', '12:00', '17:00'],
    primaryPurpose: ['engage', 'educate', 'authority', 'entertain'],
    contentRatio: {
      educate: 25,
      entertain: 20,
      inspire: 10,
      sell: 5,
      engage: 20,
      convert: 5,
      authority: 10,
      community: 5,
      culture: 0,
    },
  },
  facebook: {
    id: 'facebook',
    label: 'Facebook',
    icon: 'facebook',
    description: 'Comunidades e grupos. Eventos locais. 30+ audience.',
    audience: 'Brasileiros 30-55. Grupos de cidade e interesse.',
    formats: ['fb_post', 'fb_reels', 'fb_story', 'event', 'group_post', 'fb_live'],
    bestDays: ['Wed', 'Thu', 'Fri', 'Sat'],
    bestTimes: ['09:00', '13:00', '15:00'],
    primaryPurpose: ['community', 'educate', 'entertain', 'culture'],
    contentRatio: {
      educate: 20,
      entertain: 20,
      inspire: 10,
      sell: 10,
      engage: 15,
      convert: 5,
      authority: 0,
      community: 15,
      culture: 5,
    },
  },
  whatsapp: {
    id: 'whatsapp',
    label: 'WhatsApp',
    icon: 'message-circle',
    description: 'Comunidade fechada. Updates rápidos e pessoais.',
    audience: 'Membros da comunidade Muuday. Engajamento alto.',
    formats: ['status_text', 'status_image', 'status_video', 'community_announcement', 'broadcast'],
    bestDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    bestTimes: ['08:00', '12:00', '18:00'],
    primaryPurpose: ['community', 'educate', 'engage'],
    contentRatio: {
      educate: 30,
      entertain: 10,
      inspire: 5,
      sell: 10,
      engage: 20,
      convert: 5,
      authority: 0,
      community: 15,
      culture: 5,
    },
  },
  newsletter: {
    id: 'newsletter',
    label: 'Newsletter',
    icon: 'mail',
    description: 'Conteúdo premium aprofundado. Relação direta com audiência.',
    audience: 'Assinantes engajados. Brasileiros no exterior.',
    formats: ['solo', 'digest', 'sequence', 'welcome'],
    bestDays: ['Tue', 'Thu'],
    bestTimes: ['08:00'],
    primaryPurpose: ['educate', 'authority', 'inspire', 'convert'],
    contentRatio: {
      educate: 40,
      entertain: 5,
      inspire: 15,
      sell: 10,
      engage: 10,
      convert: 10,
      authority: 5,
      community: 5,
      culture: 0,
    },
  },
}

export const FORMATS: Record<ContentFormat, FormatConfig> = {
  feed_photo: {
    id: 'feed_photo',
    label: 'Foto no Feed',
    description: 'Imagem única com legenda. Post clássico do Instagram.',
    icon: 'image',
    visualType: 'image',
    aspectRatio: '4:5',
    maxLength: '2200 chars',
    requiresVisual: true,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: '3-4x/semana',
    bestTimeToPost: '12:00 ou 18:00',
    engagementLevel: 'medium',
    productionEffort: 'low',
  },
  carousel: {
    id: 'carousel',
    label: 'Carrossel',
    description: '3-10 slides com storytelling visual. Alto engajamento e saves.',
    icon: 'images',
    visualType: 'image',
    aspectRatio: '1:1',
    maxLength: '2200 chars',
    requiresVisual: true,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: '2-3x/semana',
    bestTimeToPost: '08:00 ou 18:00',
    engagementLevel: 'high',
    productionEffort: 'medium',
  },
  reels: {
    id: 'reels',
    label: 'Reels',
    description: 'Vídeo curto vertical 15-90s. Maior alcance orgânico do IG.',
    icon: 'play',
    visualType: 'video',
    aspectRatio: '9:16',
    maxDuration: '90s',
    maxLength: '2200 chars',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '4-7x/semana',
    bestTimeToPost: '07:00, 12:00, 19:00',
    engagementLevel: 'high',
    productionEffort: 'high',
  },
  story: {
    id: 'story',
    label: 'Story',
    description: 'Conteúdo efêmero 24h. Engajamento direto e interação.',
    icon: 'smartphone',
    visualType: 'mixed',
    aspectRatio: '9:16',
    maxDuration: '60s',
    maxLength: '500 chars',
    requiresVisual: true,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: 'diário (3-7x)',
    bestTimeToPost: '08:00, 12:00, 18:00, 21:00',
    engagementLevel: 'high',
    productionEffort: 'low',
  },
  story_highlight: {
    id: 'story_highlight',
    label: 'Destaque',
    description: 'Stories salvos permanentemente no perfil. Organizado por tema.',
    icon: 'bookmark',
    visualType: 'mixed',
    aspectRatio: '9:16',
    maxDuration: '60s',
    requiresVisual: true,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: 'semanal (atualizar)',
    bestTimeToPost: 'n/a',
    engagementLevel: 'low',
    productionEffort: 'medium',
  },
  live: {
    id: 'live',
    label: 'Live',
    description: 'Transmissão ao vivo. Q&A, entrevistas, anúncios.',
    icon: 'radio',
    visualType: 'video',
    aspectRatio: '9:16',
    maxDuration: '4h',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'semanal',
    bestTimeToPost: '20:00',
    engagementLevel: 'high',
    productionEffort: 'high',
  },
  ugc: {
    id: 'ugc',
    label: 'UGC',
    description: 'Conteúdo gerado por usuários. Repost com permissão.',
    icon: 'users',
    visualType: 'mixed',
    aspectRatio: '9:16',
    maxDuration: '90s',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '2-3x/semana',
    bestTimeToPost: '12:00 ou 18:00',
    engagementLevel: 'high',
    productionEffort: 'low',
  },
  meme: {
    id: 'meme',
    label: 'Meme',
    description: 'Humor cultural brasileiro. Alta viralização e compartilhamento.',
    icon: 'smile',
    visualType: 'image',
    aspectRatio: '1:1',
    maxLength: '500 chars',
    requiresVisual: true,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: '2-3x/semana',
    bestTimeToPost: '12:00 ou 18:00',
    engagementLevel: 'high',
    productionEffort: 'low',
  },
  short_video: {
    id: 'short_video',
    label: 'Vídeo Curto',
    description: 'Vídeo 15-90s. Hook nos primeiros 3s. Sound-on.',
    icon: 'play',
    visualType: 'video',
    aspectRatio: '9:16',
    maxDuration: '90s',
    maxLength: '2200 chars',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '1-3x/dia',
    bestTimeToPost: '07:00, 12:00, 19:00',
    engagementLevel: 'high',
    productionEffort: 'high',
  },
  duet: {
    id: 'duet',
    label: 'Dueto',
    description: 'Reagir a vídeo de outro creator. Engajamento cruzado.',
    icon: 'git-branch',
    visualType: 'video',
    aspectRatio: '9:16',
    maxDuration: '60s',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '1-2x/semana',
    bestTimeToPost: '12:00 ou 19:00',
    engagementLevel: 'high',
    productionEffort: 'medium',
  },
  stitch: {
    id: 'stitch',
    label: 'Stitch',
    description: 'Continuar história de outro vídeo. Resposta criativa.',
    icon: 'scissors',
    visualType: 'video',
    aspectRatio: '9:16',
    maxDuration: '60s',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '1-2x/semana',
    bestTimeToPost: '12:00 ou 19:00',
    engagementLevel: 'high',
    productionEffort: 'medium',
  },
  photo_carousel: {
    id: 'photo_carousel',
    label: 'Carrossel de Fotos',
    description: '2-35 fotos com música. Formato crescente no TikTok.',
    icon: 'images',
    visualType: 'image',
    aspectRatio: '9:16',
    maxLength: '2200 chars',
    requiresVisual: true,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: '2-3x/semana',
    bestTimeToPost: '12:00 ou 19:00',
    engagementLevel: 'medium',
    productionEffort: 'low',
  },
  tiktok_live: {
    id: 'tiktok_live',
    label: 'Live',
    description: 'Transmissão ao vivo no TikTok. Interação em tempo real.',
    icon: 'radio',
    visualType: 'video',
    aspectRatio: '9:16',
    maxDuration: '4h',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'semanal',
    bestTimeToPost: '20:00',
    engagementLevel: 'high',
    productionEffort: 'high',
  },
  tiktok_ugc: {
    id: 'tiktok_ugc',
    label: 'UGC',
    description: 'Conteúdo de usuários. Stitch/duet ou repost.',
    icon: 'users',
    visualType: 'video',
    aspectRatio: '9:16',
    maxDuration: '90s',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '2-3x/semana',
    bestTimeToPost: '12:00 ou 19:00',
    engagementLevel: 'high',
    productionEffort: 'low',
  },
  long_video: {
    id: 'long_video',
    label: 'Vídeo Longo',
    description: 'Vídeo 5-20min. SEO, tutoriais, documentários.',
    icon: 'video',
    visualType: 'video',
    aspectRatio: '16:9',
    maxDuration: '20min',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '1-2x/semana',
    bestTimeToPost: '14:00, 16:00',
    engagementLevel: 'medium',
    productionEffort: 'high',
  },
  youtube_shorts: {
    id: 'youtube_shorts',
    label: 'Shorts',
    description: 'Vídeo vertical 60s. Alcance rápido, funnel para longos.',
    icon: 'smartphone',
    visualType: 'video',
    aspectRatio: '9:16',
    maxDuration: '60s',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '3-5x/semana',
    bestTimeToPost: '12:00, 18:00',
    engagementLevel: 'high',
    productionEffort: 'medium',
  },
  community_post: {
    id: 'community_post',
    label: 'Post da Comunidade',
    description: 'Post de texto/imagem no feed da comunidade. Engage inscritos.',
    icon: 'message-square',
    visualType: 'text',
    aspectRatio: '1:1',
    maxLength: '1500 chars',
    requiresVisual: false,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: '2-3x/semana',
    bestTimeToPost: '12:00',
    engagementLevel: 'medium',
    productionEffort: 'low',
  },
  podcast_video: {
    id: 'podcast_video',
    label: 'Podcast',
    description: 'Episódio de podcast em vídeo. 20-60min. Conversas profundas.',
    icon: 'mic',
    visualType: 'video',
    aspectRatio: '16:9',
    maxDuration: '60min',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'semanal',
    bestTimeToPost: '08:00',
    engagementLevel: 'medium',
    productionEffort: 'high',
  },
  text_post: {
    id: 'text_post',
    label: 'Post de Texto',
    description: 'Post sem mídia. Story + insight. Alto alcance no LinkedIn.',
    icon: 'file-text',
    visualType: 'text',
    aspectRatio: 'text',
    maxLength: '3000 chars',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '3-5x/semana',
    bestTimeToPost: '08:00, 12:00, 17:00',
    engagementLevel: 'medium',
    productionEffort: 'low',
  },
  single_image: {
    id: 'single_image',
    label: 'Imagem Única',
    description: 'Post com uma imagem 1200x627. Insight visual.',
    icon: 'image',
    visualType: 'image',
    aspectRatio: '1200:627',
    maxLength: '3000 chars',
    requiresVisual: true,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: '2-3x/semana',
    bestTimeToPost: '08:00, 12:00',
    engagementLevel: 'medium',
    productionEffort: 'low',
  },
  document_carousel: {
    id: 'document_carousel',
    label: 'PDF Carrossel',
    description: 'Documento PDF multi-página. Alta retenção e saves.',
    icon: 'file',
    visualType: 'image',
    aspectRatio: '1:1',
    maxLength: '3000 chars',
    requiresVisual: true,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: '1-2x/semana',
    bestTimeToPost: '08:00, 12:00',
    engagementLevel: 'high',
    productionEffort: 'medium',
  },
  video_post: {
    id: 'video_post',
    label: 'Vídeo',
    description: 'Vídeo nativo LinkedIn. 30s-10min.',
    icon: 'play',
    visualType: 'video',
    aspectRatio: '1:1',
    maxDuration: '10min',
    maxLength: '3000 chars',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '1x/semana',
    bestTimeToPost: '12:00, 17:00',
    engagementLevel: 'high',
    productionEffort: 'high',
  },
  linkedin_newsletter: {
    id: 'linkedin_newsletter',
    label: 'Newsletter',
    description: 'Artigo longo enviado aos seguidores. Autoridade profunda.',
    icon: 'mail',
    visualType: 'text',
    aspectRatio: 'text',
    maxLength: '120000 chars',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'semanal ou quinzenal',
    bestTimeToPost: '08:00',
    engagementLevel: 'medium',
    productionEffort: 'high',
  },
  poll: {
    id: 'poll',
    label: 'Enquete',
    description: 'Enquete com 2-4 opções. Engajamento rápido e dados.',
    icon: 'bar-chart-2',
    visualType: 'text',
    aspectRatio: 'text',
    maxLength: '140 chars',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '1x/semana',
    bestTimeToPost: '12:00',
    engagementLevel: 'high',
    productionEffort: 'low',
  },
  article: {
    id: 'article',
    label: 'Artigo',
    description: 'Artigo longo no LinkedIn Publishing. SEO + autoridade.',
    icon: 'file-text',
    visualType: 'text',
    aspectRatio: 'text',
    maxLength: '120000 chars',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'quinzenal',
    bestTimeToPost: '08:00',
    engagementLevel: 'low',
    productionEffort: 'high',
  },
  text_tweet: {
    id: 'text_tweet',
    label: 'Tweet',
    description: 'Tweet simples 280 chars. Opinião ou dica rápida.',
    icon: 'message-circle',
    visualType: 'text',
    aspectRatio: 'text',
    maxLength: '280 chars',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '1-3x/dia',
    bestTimeToPost: '08:00, 12:00, 17:00',
    engagementLevel: 'medium',
    productionEffort: 'low',
  },
  thread: {
    id: 'thread',
    label: 'Thread',
    description: 'Série de tweets conectados. storytelling ou tutorial.',
    icon: 'list',
    visualType: 'text',
    aspectRatio: 'text',
    maxLength: '25 tweets',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '2-3x/semana',
    bestTimeToPost: '08:00, 12:00',
    engagementLevel: 'high',
    productionEffort: 'medium',
  },
  image_tweet: {
    id: 'image_tweet',
    label: 'Tweet com Imagem',
    description: 'Tweet + imagem. Dobra o engajamento.',
    icon: 'image',
    visualType: 'image',
    aspectRatio: '16:9',
    maxLength: '280 chars',
    requiresVisual: true,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: '2-3x/semana',
    bestTimeToPost: '12:00, 17:00',
    engagementLevel: 'high',
    productionEffort: 'low',
  },
  video_tweet: {
    id: 'video_tweet',
    label: 'Tweet com Vídeo',
    description: 'Tweet + vídeo nativo. Alta retenção.',
    icon: 'play',
    visualType: 'video',
    aspectRatio: '16:9',
    maxDuration: '2min20s',
    maxLength: '280 chars',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '1-2x/semana',
    bestTimeToPost: '12:00, 17:00',
    engagementLevel: 'high',
    productionEffort: 'medium',
  },
  spaces: {
    id: 'spaces',
    label: 'Spaces',
    description: 'Áudio ao vivo no Twitter. Conversas e debates.',
    icon: 'mic',
    visualType: 'audio',
    aspectRatio: 'text',
    maxDuration: '4h',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'quinzenal',
    bestTimeToPost: '20:00',
    engagementLevel: 'medium',
    productionEffort: 'medium',
  },
  fb_post: {
    id: 'fb_post',
    label: 'Post no Feed',
    description: 'Post no feed com texto/imagem/vídeo. Alcance orgânico baixo.',
    icon: 'file-text',
    visualType: 'mixed',
    aspectRatio: '1:1',
    maxLength: '63206 chars',
    requiresVisual: false,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: '3-5x/semana',
    bestTimeToPost: '09:00, 13:00, 15:00',
    engagementLevel: 'low',
    productionEffort: 'low',
  },
  fb_reels: {
    id: 'fb_reels',
    label: 'Reels',
    description: 'Vídeo curto no Facebook. Mesmo conteúdo do IG Reels.',
    icon: 'play',
    visualType: 'video',
    aspectRatio: '9:16',
    maxDuration: '90s',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '3-5x/semana',
    bestTimeToPost: '12:00, 18:00',
    engagementLevel: 'medium',
    productionEffort: 'high',
  },
  fb_story: {
    id: 'fb_story',
    label: 'Story',
    description: 'Story no Facebook. Cross-post do IG.',
    icon: 'smartphone',
    visualType: 'mixed',
    aspectRatio: '9:16',
    maxDuration: '60s',
    requiresVisual: true,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: 'diário',
    bestTimeToPost: '12:00, 18:00',
    engagementLevel: 'medium',
    productionEffort: 'low',
  },
  event: {
    id: 'event',
    label: 'Evento',
    description: 'Evento no Facebook. Encontros, lives, workshops.',
    icon: 'calendar',
    visualType: 'image',
    aspectRatio: '1:1',
    requiresVisual: true,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: 'mensal',
    bestTimeToPost: 'n/a',
    engagementLevel: 'medium',
    productionEffort: 'medium',
  },
  group_post: {
    id: 'group_post',
    label: 'Post em Grupo',
    description: 'Post em grupos de comunidade brasileira. Alto engajamento.',
    icon: 'users',
    visualType: 'mixed',
    aspectRatio: '1:1',
    maxLength: '63206 chars',
    requiresVisual: false,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: '3-4x/semana',
    bestTimeToPost: '09:00, 12:00',
    engagementLevel: 'high',
    productionEffort: 'low',
  },
  fb_live: {
    id: 'fb_live',
    label: 'Live',
    description: 'Transmissão ao vivo no Facebook.',
    icon: 'radio',
    visualType: 'video',
    aspectRatio: '9:16',
    maxDuration: '8h',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'semanal',
    bestTimeToPost: '20:00',
    engagementLevel: 'medium',
    productionEffort: 'high',
  },
  status_text: {
    id: 'status_text',
    label: 'Status de Texto',
    description: 'Status de texto. Frase curta, inspiração ou dica.',
    icon: 'type',
    visualType: 'text',
    aspectRatio: '9:16',
    maxLength: '700 chars',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'diário',
    bestTimeToPost: '08:00, 12:00, 18:00',
    engagementLevel: 'medium',
    productionEffort: 'low',
  },
  status_image: {
    id: 'status_image',
    label: 'Status de Imagem',
    description: 'Status com imagem + texto. Quotes, dicas visuais.',
    icon: 'image',
    visualType: 'image',
    aspectRatio: '9:16',
    maxLength: '700 chars',
    requiresVisual: true,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: 'diário',
    bestTimeToPost: '08:00, 12:00, 18:00',
    engagementLevel: 'medium',
    productionEffort: 'low',
  },
  status_video: {
    id: 'status_video',
    label: 'Status de Vídeo',
    description: 'Status com vídeo curto. Dica rápida ou momento.',
    icon: 'play',
    visualType: 'video',
    aspectRatio: '9:16',
    maxDuration: '60s',
    maxLength: '700 chars',
    requiresVisual: true,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: '2-3x/semana',
    bestTimeToPost: '12:00, 18:00',
    engagementLevel: 'high',
    productionEffort: 'medium',
  },
  community_announcement: {
    id: 'community_announcement',
    label: 'Anúncio da Comunidade',
    description: 'Anúncio oficial na comunidade WhatsApp.',
    icon: 'megaphone',
    visualType: 'mixed',
    aspectRatio: '9:16',
    maxLength: '2048 chars',
    requiresVisual: false,
    aiGeneratesVisual: true,
    aiGeneratesCopy: true,
    suggestedCadence: '2-3x/semana',
    bestTimeToPost: '08:00, 18:00',
    engagementLevel: 'medium',
    productionEffort: 'low',
  },
  broadcast: {
    id: 'broadcast',
    label: 'Broadcast',
    description: 'Mensagem em broadcast para lista. Personal mas em massa.',
    icon: 'send',
    visualType: 'text',
    aspectRatio: 'text',
    maxLength: '4096 chars',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'semanal',
    bestTimeToPost: '08:00',
    engagementLevel: 'medium',
    productionEffort: 'low',
  },
  solo: {
    id: 'solo',
    label: 'Email Solo',
    description: 'Um único tema aprofundado. 500-1500 palavras.',
    icon: 'mail',
    visualType: 'text',
    aspectRatio: 'text',
    maxLength: '10000 chars',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'semanal',
    bestTimeToPost: '08:00',
    engagementLevel: 'medium',
    productionEffort: 'medium',
  },
  digest: {
    id: 'digest',
    label: 'Resumo Semanal',
    description: 'Curadoria de conteúdo da semana. Links + comentários.',
    icon: 'book-open',
    visualType: 'text',
    aspectRatio: 'text',
    maxLength: '5000 chars',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'semanal (sexta)',
    bestTimeToPost: '08:00',
    engagementLevel: 'medium',
    productionEffort: 'medium',
  },
  sequence: {
    id: 'sequence',
    label: 'Sequência',
    description: 'Série de emails automáticos. Onboarding, curso, etc.',
    icon: 'layers',
    visualType: 'text',
    aspectRatio: 'text',
    maxLength: '5000 chars/email',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'automático',
    bestTimeToPost: 'automático',
    engagementLevel: 'medium',
    productionEffort: 'high',
  },
  welcome: {
    id: 'welcome',
    label: 'Boas-vindas',
    description: 'Email de boas-vindas para novos assinantes.',
    icon: 'hand',
    visualType: 'text',
    aspectRatio: 'text',
    maxLength: '3000 chars',
    requiresVisual: false,
    aiGeneratesVisual: false,
    aiGeneratesCopy: true,
    suggestedCadence: 'automático',
    bestTimeToPost: 'automático',
    engagementLevel: 'medium',
    productionEffort: 'low',
  },
}

export const PURPOSES: Record<
  ContentPurpose,
  { label: string; description: string; icon: string }
> = {
  educate: {
    label: 'Educar',
    description: 'Ensinar algo útil. Como fazer X, explicar Y, dicas práticas.',
    icon: 'graduation-cap',
  },
  entertain: {
    label: 'Entreter',
    description: 'Fazer rir, surpreender, contar histórias divertidas.',
    icon: 'smile',
  },
  inspire: {
    label: 'Inspirar',
    description: 'Motivar, mostrar possibilidades, histórias de superação.',
    icon: 'sparkles',
  },
  sell: {
    label: 'Vender',
    description: 'Promover produto/serviço diretamente.',
    icon: 'shopping-bag',
  },
  engage: {
    label: 'Engajar',
    description: 'Gerar interação. Perguntas, debates, enquetes.',
    icon: 'message-circle',
  },
  convert: {
    label: 'Converter',
    description: 'Levar para próxima etapa. Cadastro, download, compra.',
    icon: 'target',
  },
  authority: {
    label: 'Autoridade',
    description: 'Mostrar expertise. Opinião, case study, dados.',
    icon: 'award',
  },
  community: {
    label: 'Comunidade',
    description: 'Fortalecer pertencimento. Reconhecer membros, criar conexão.',
    icon: 'users',
  },
  culture: {
    label: 'Cultura',
    description: 'Celebrar cultura brasileira. Saudade, tradições, identidade.',
    icon: 'heart',
  },
}

export function getFormatsForPlatform(platform: ContentPlatform): ContentFormat[] {
  return PLATFORMS[platform]?.formats || []
}

export function getPlatformForFormat(format: ContentFormat): ContentPlatform | undefined {
  for (const [platform, config] of Object.entries(PLATFORMS)) {
    if (config.formats.includes(format)) return platform as ContentPlatform
  }
  return undefined
}

export function getSuggestedPurpose(platform: ContentPlatform): ContentPurpose[] {
  const platformConfig = PLATFORMS[platform]
  if (!platformConfig) return ['educate']
  return Object.entries(platformConfig.contentRatio)
    .sort((a, b) => b[1] - a[1])
    .map(([p]) => p as ContentPurpose)
}

export function getDefaultTopic(pillar: string, purpose: ContentPurpose): string {
  const topics: Record<string, Record<ContentPurpose, string>> = {
    finance: {
      educate: 'Como economizar nos primeiros 6 meses no exterior',
      entertain: 'As coisas mais caras que brasileiros compram sem perceber',
      inspire: 'Como eu paguei £20k de dívida em 2 anos no UK',
      sell: 'Guia completo de impostos para brasileiros no UK',
      engage: 'Qual foi a compra mais absurda que você fez no exterior?',
      convert: 'Checklist gratuito: Primeiros 30 dias de finanças no UK',
      authority: 'Análise: O que mudou no mercado de câmbio em 2025',
      community: 'Como a comunidade brasileira do UK divide dicas de desconto',
      culture: 'Saudade do preço da coxinha? A realidade do custo de vida no exterior',
    },
    career: {
      educate: 'Como adaptar seu CV para o mercado britânico',
      entertain: 'Entrevistas de emprego que deram completamente errado',
      inspire: 'De estagiário a diretor: história de um brasileiro no exterior',
      sell: 'Curso de LinkedIn para brasileiros no UK',
      engage: 'Qual foi a pergunta mais difícil da sua entrevista?',
      convert: 'Template de CV aprovado por recrutadores britânicos',
      authority: '5 tendências do mercado de tech no UK para 2025',
      community: 'Networking entre brasileiros: como se ajudam no LinkedIn',
      culture: 'Como a cultura brasileira de networking se adapta no exterior',
    },
    immigration: {
      educate: 'Passo a passo do visto de trabalho tier 2',
      entertain: 'Burocracias absurdas que só brasileiro no exterior entende',
      inspire: 'Depois de 3 negativas, finalmente consegui meu visto',
      sell: 'Consultoria de imigração para brasileiros no UK',
      engage: 'Qual documento foi o mais difícil de conseguir?',
      convert: 'Checklist de documentos para o visto de skilled worker',
      authority: 'Mudanças na política de imigração UK 2025',
      community: 'Grupos de apoio para brasileiros no processo de visto',
      culture: 'Manter documentos brasileiros válidos morando no exterior',
    },
    lifestyle: {
      educate: 'Guia completo de aluguel no primeiro ano no UK',
      entertain: 'Coisas que brasileiros fazem que confundem britânicos',
      inspire: 'Como montei minha casa do zero com £500',
      sell: 'Ebook de sobrevivência no primeiro ano no exterior',
      engage: 'O que você mais sente falta do Brasil?',
      convert: 'Guia de bairros de Londres para brasileiros',
      authority: 'Análise: Qual cidade do UK tem melhor custo-benefício',
      community: 'Encontros de brasileiros em cada cidade do UK',
      culture: 'Sábado sem feijoada: como recriar ritual brasileiro no exterior',
    },
    community: {
      educate: 'Como fazer amigos no exterior: guia prático',
      entertain: 'Tinder no exterior: histórias de brasileiros',
      inspire: 'De sozinho para comunidade: minha jornada no UK',
      sell: 'Evento presencial de networking para brasileiros',
      engage: 'Como você conheceu seus primeiros amigos no exterior?',
      convert: 'Entre na comunidade Muuday no WhatsApp',
      authority: 'Estudo: Loneliness entre imigrantes brasileiros',
      community: 'Destaque do membro da semana: Maria do UK',
      culture: 'Saudades de estar em casa: como a comunidade substitui',
    },
    culture: {
      educate: 'História da imigração brasileira no UK',
      entertain: 'Memes que só brasileiro no exterior entende',
      inspire: 'Como criei um pedacinho do Brasil na minha casa no UK',
      sell: 'Cesta de produtos brasileiros no UK',
      engage: 'Qual comida brasileira você mais sente falta?',
      convert: 'Mapa dos melhores restaurantes brasileiros no UK',
      authority: 'Impacto da cultura brasileira no mercado de trabalho UK',
      community: 'Festa junina no Hyde Park: como brasileiros se reúnem',
      culture: 'Saudade não é só lugar: é sensação, é cheiro, é gente',
    },
  }
  return topics[pillar]?.[purpose] || `Conteúdo sobre ${pillar}`
}
