export type { ThemeTemplate, SlideData } from './types'
export { editorialTheme } from './editorial'
export { minimalTheme } from './minimal'
export { boldTheme } from './bold'
export { darkTheme } from './dark'
export { warmTheme } from './warm'
